### ISSUE TITLE
u-boot (next) fails to compile on 22.04

### ISSUE THREAD

**Issue by cvanallen99** [orangepi-xunlong/orangepi-build#163]
Using a 22.04 docker container with mirrors.tuna.tsinghua.edu.cn for all of the repo sources, u-boot fails to compile.  Looks similar to the other reports but line numbers are different and mine makes it to BINMAN before it fails.

...
..
  AR      spl/drivers/power/built-in.o
  AR      spl/drivers/serial/built-in.o
  AR      spl/drivers/built-in.o
  LD      spl/u-boot-spl
  OBJCOPY spl/u-boot-spl-nodtb.bin
  SYM     spl/u-boot-spl.sym
  COPY    spl/u-boot-spl.bin
  MKIMAGE spl/sunxi-spl.bin
  BINMAN  all
[ error ] ERROR in function compile_uboot [ ./build.sh:305 -> scripts/main.sh:638 -> scripts/main.sh:524 -> scripts/compilation.sh:256 -> scripts/general.sh:0 ]
[ error ] U-boot compilation failed
[ o.k. ] Process terminated

**Comment by leeboby** [comment]
orangepi-build currently cannot be guaranteed to work in Docker. Please try using a physical machine or a VirtualBox virtual machine. Thanks!
